export const footerLinks = [
  {
    title: "회사 소개",
    links: [
      { title: "사업소개", url: "/" },
      { title: "투자정보", url: "/" },
      { title: "홍보센터", url: "/" },
      { title: "채용정보", url: "/" },
    ],
  },
  {
    title: "고객센터",
    links: [
      { title: "자주묻는질문", url: "/" },
      { title: "일반문의", url: "/" },
      { title: "업무제휴문의", url: "/" },
    ],
  },
  {
    title: "SNS",
    links: [
      { title: "카카오톡", url: "/" },
      { title: "인스타그램", url: "/" },
      { title: "페이스북", url: "/" },
    ],
  },
];

export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];
